-- Minimal version - Just table creation statements
-- Copy this entire file or paste in chunks

CREATE TABLE IF NOT EXISTS profiles (id uuid primary key references auth.users, name text, preferences jsonb);
CREATE TABLE IF NOT EXISTS pantry_items (id bigint generated always as identity primary key, user_id uuid references profiles(id), ingredient text not null, quantity int default 1);
CREATE TABLE IF NOT EXISTS recipes (id bigint generated always as identity primary key, user_id uuid references profiles(id), title text, details jsonb, calories int, time text);
CREATE TABLE IF NOT EXISTS favorites (id bigint generated always as identity primary key, user_id uuid references profiles(id), recipe_id bigint references recipes(id));

CREATE TABLE IF NOT EXISTS analytics_events (id uuid primary key default gen_random_uuid(), event_type text not null, user_id uuid references profiles(id), session_id text not null, properties jsonb default '{}', timestamp timestamptz default now(), page_url text, user_agent text);
CREATE TABLE IF NOT EXISTS recipe_metrics (id bigint generated always as identity primary key, recipe_id bigint references recipes(id), user_id uuid references profiles(id), generated_at timestamptz default now(), ingredients_used text[] not null, cuisine_type text, cook_time text not null, calories int not null, feedback_score int check (feedback_score >= 1 and feedback_score <= 5), api_latency_ms int not null, model_used text not null, retry_count int default 0);
CREATE TABLE IF NOT EXISTS system_metrics (id uuid primary key default gen_random_uuid(), metric_type text not null check (metric_type in ('api_performance', 'user_engagement', 'error_rate', 'cost_analysis')), value numeric not null, metadata jsonb default '{}', timestamp timestamptz default now());
CREATE TABLE IF NOT EXISTS logs (id uuid primary key default gen_random_uuid(), level text not null check (level in ('error', 'warn', 'info', 'debug')), message text not null, context jsonb default '{}', user_id uuid references profiles(id), session_id text, stack_trace text, timestamp timestamptz default now(), source text not null check (source in ('frontend', 'api', 'edge_function', 'system')), component text);
CREATE TABLE IF NOT EXISTS error_reports (id uuid primary key default gen_random_uuid(), error_type text not null, message text not null, stack_trace text, user_id uuid references profiles(id), session_id text, context jsonb default '{}', resolved boolean default false, created_at timestamptz default now(), resolved_at timestamptz);
CREATE TABLE IF NOT EXISTS recipe_feedback (id bigint generated always as identity primary key, recipe_id bigint references recipes(id), user_id uuid references profiles(id), feedback_type text not null check (feedback_type in ('thumbs_up', 'thumbs_down', 'rating')), score int check (score >= 1 and score <= 5), feedback_text text, created_at timestamptz default now());
CREATE TABLE IF NOT EXISTS ai_config (id uuid primary key default gen_random_uuid(), model_name text not null, system_prompt text not null, message_templates jsonb not null, version text not null, is_active boolean default false, created_at timestamptz default now(), performance_score numeric, metadata jsonb default '{}');
CREATE TABLE IF NOT EXISTS workflow_state (id uuid primary key default gen_random_uuid(), workflow_name text not null, status text not null check (status in ('pending', 'running', 'completed', 'failed')), current_step text, progress_percentage int default 0, metadata jsonb default '{}', started_at timestamptz default now(), completed_at timestamptz, error_message text);

CREATE TABLE IF NOT EXISTS tenants (id uuid primary key default gen_random_uuid(), name text not null, plan text default 'free' check (plan in ('free', 'pro', 'family')), stripe_customer_id text, stripe_subscription_id text, status text default 'active' check (status in ('active', 'inactive', 'suspended', 'cancelled')), created_at timestamp with time zone default now(), updated_at timestamp with time zone default now(), settings jsonb default '{}', metadata jsonb default '{}');
CREATE TABLE IF NOT EXISTS tenant_memberships (id uuid primary key default gen_random_uuid(), tenant_id uuid references tenants(id) on delete cascade, user_id uuid references auth.users(id) on delete cascade, role text not null check (role in ('owner', 'editor', 'viewer')), invited_by uuid references auth.users(id), joined_at timestamp with time zone default now(), status text default 'active' check (status in ('active', 'pending', 'suspended')), unique(tenant_id, user_id));
CREATE TABLE IF NOT EXISTS subscriptions (id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id), tenant_id uuid references tenants(id), stripe_customer_id text, stripe_subscription_id text unique, plan text not null check (plan in ('free', 'pro', 'family')), status text not null check (status in ('active', 'canceled', 'incomplete', 'incomplete_expired', 'past_due', 'trialing', 'unpaid')), current_period_start timestamp with time zone, current_period_end timestamp with time zone, cancel_at_period_end boolean default false, created_at timestamp with time zone default now(), updated_at timestamp with time zone default now(), metadata jsonb default '{}');
CREATE TABLE IF NOT EXISTS usage_logs (id bigint primary key generated always as identity, user_id uuid references auth.users(id), tenant_id uuid references tenants(id), action text not null, tokens_used int default 0, cost_usd numeric(10,4) default 0, model_used text, timestamp timestamp with time zone default now(), metadata jsonb default '{}');
CREATE TABLE IF NOT EXISTS tenant_invites (id uuid primary key default gen_random_uuid(), tenant_id uuid references tenants(id) on delete cascade, email text not null, role text not null check (role in ('editor', 'viewer')), invited_by uuid references auth.users(id), token text unique not null, expires_at timestamp with time zone not null, used_at timestamp with time zone, created_at timestamp with time zone default now());
CREATE TABLE IF NOT EXISTS ai_cache (id uuid primary key default gen_random_uuid(), tenant_id uuid references tenants(id) on delete cascade, cache_key text not null, prompt_hash text not null, response_data jsonb not null, model_used text not null, tokens_used int not null, cost_usd numeric(10,4) not null, ttl_seconds int not null, created_at timestamp with time zone default now(), expires_at timestamp with time zone not null, unique(tenant_id, cache_key));
CREATE TABLE IF NOT EXISTS billing_events (id uuid primary key default gen_random_uuid(), stripe_event_id text unique not null, event_type text not null, processed boolean default false, data jsonb not null, created_at timestamp with time zone default now());

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'profiles' AND column_name = 'tenant_id') THEN ALTER TABLE profiles ADD COLUMN tenant_id uuid references tenants(id); END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'profiles' AND column_name = 'role') THEN ALTER TABLE profiles ADD COLUMN role text default 'owner' check (role in ('owner', 'editor', 'viewer')); END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'pantry_items' AND column_name = 'tenant_id') THEN ALTER TABLE pantry_items ADD COLUMN tenant_id uuid references tenants(id); END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'recipes' AND column_name = 'tenant_id') THEN ALTER TABLE recipes ADD COLUMN tenant_id uuid references tenants(id); END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'favorites' AND column_name = 'tenant_id') THEN ALTER TABLE favorites ADD COLUMN tenant_id uuid references tenants(id); END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'analytics_events' AND column_name = 'tenant_id') THEN ALTER TABLE analytics_events ADD COLUMN tenant_id uuid references tenants(id); END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'recipe_metrics' AND column_name = 'tenant_id') THEN ALTER TABLE recipe_metrics ADD COLUMN tenant_id uuid references tenants(id); END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'recipe_feedback' AND column_name = 'tenant_id') THEN ALTER TABLE recipe_feedback ADD COLUMN tenant_id uuid references tenants(id); END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'pantry_items' AND column_name = 'is_sample') THEN ALTER TABLE pantry_items ADD COLUMN is_sample boolean default false; END IF;
END $$;
