// [STAKE+TRUST:BEGIN:privacy_page]
"use client";

import { Metadata } from "next";
import { readFile } from "fs/promises";
import path from "path";

export const metadata: Metadata = {
  title: "Privacy Policy - What's for Dinner?",
  description: "Our privacy policy explains how we collect, use, and protect your data.",
};

export default async function PrivacyPage() {
  // In production, you might want to fetch this from a CMS or API
  // For now, we'll render a simple page with a link to the full policy
  return (
    <div className="container mx-auto px-4 py-12 max-w-4xl">
      <div className="mb-8">
        <h1 className="text-4xl font-bold mb-4">Privacy Policy</h1>
        <p className="text-muted-foreground text-lg">
          Your privacy is important to us. This policy explains how we collect, use, and protect your data.
        </p>
      </div>

      <div className="prose dark:prose-invert max-w-none">
        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">Plain-Language Summary</h2>
          <p className="text-muted-foreground mb-4">
            We collect data you provide (account info, pantry items) and data generated by using the service 
            (recipe preferences, usage patterns). We use this data to provide meal planning, improve the service, 
            and ensure security. We don't sell your data to third parties. You can export, correct, or delete 
            your data at any time.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">Key Points</h2>
          <ul className="list-disc pl-5 space-y-2 text-muted-foreground">
            <li>We collect only the data necessary to provide the service</li>
            <li>We never sell your personal information</li>
            <li>You can export, correct, or delete your data at any time</li>
            <li>We follow GDPR, PIPEDA, and other applicable privacy laws</li>
            <li>We use industry-standard security practices</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">Your Rights</h2>
          <div className="space-y-4">
            <div>
              <h3 className="text-xl font-semibold mb-2">Right to Access</h3>
              <p className="text-muted-foreground">
                Request a copy of all personal data we hold about you.{" "}
                <a href="/account/export" className="text-primary hover:underline">
                  Export My Data →
                </a>
              </p>
            </div>
            <div>
              <h3 className="text-xl font-semibold mb-2">Right to Rectification</h3>
              <p className="text-muted-foreground">
                Correct inaccurate personal data. Edit your profile in{" "}
                <a href="/settings" className="text-primary hover:underline">
                  Settings →
                </a>
              </p>
            </div>
            <div>
              <h3 className="text-xl font-semibold mb-2">Right to Erasure</h3>
              <p className="text-muted-foreground">
                Request deletion of your account and data.{" "}
                <a href="/settings/account/delete" className="text-primary hover:underline">
                  Delete Account →
                </a>
              </p>
            </div>
            <div>
              <h3 className="text-xl font-semibold mb-2">Right to Data Portability</h3>
              <p className="text-muted-foreground">
                Export your data in a machine-readable format (JSON, CSV).{" "}
                <a href="/account/export" className="text-primary hover:underline">
                  Export My Data →
                </a>
              </p>
            </div>
          </div>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">Full Privacy Policy</h2>
          <p className="text-muted-foreground mb-4">
            For the complete privacy policy, see{" "}
            <a 
              href="/docs/trust/PRIVACY_POLICY_DRAFT.md" 
              className="text-primary hover:underline"
              target="_blank"
              rel="noopener noreferrer"
            >
              Privacy Policy (Detailed)
            </a>
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">Contact</h2>
          <p className="text-muted-foreground">
            For privacy inquiries, contact us at{" "}
            <a href="mailto:privacy@whatsfordinner.com" className="text-primary hover:underline">
              privacy@whatsfordinner.com
            </a>
          </p>
        </section>
      </div>

      <div className="mt-8 pt-8 border-t">
        <p className="text-sm text-muted-foreground">
          Last Updated: 2025-01-XX | Version: 1.0.0
        </p>
      </div>
    </div>
  );
}
// [STAKE+TRUST:END:privacy_page]
