#!/usr/bin/env node
/**
 * Validation & Regression Guard
 * Re-runs selfchecks and produces before/after deltas
 */

import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join } from 'path';
import { execSync } from 'child_process';

const AUDIT_DIR = 'docs/audit_investor_suite';
const ISSUE_REGISTER_PATH = join(AUDIT_DIR, 'ISSUE_REGISTER.json');

if (!existsSync(ISSUE_REGISTER_PATH)) {
  console.error('❌ ISSUE_REGISTER.json not found. Run orchestrate_remediation.mjs first.');
  process.exit(1);
}

const issueRegister = JSON.parse(readFileSync(ISSUE_REGISTER_PATH, 'utf8'));
const validationResults = {
  timestamp: new Date().toISOString(),
  resolvedIssues: [],
  remainingIssues: [],
  regressionChecks: {},
};

console.log('🔍 Running validation checks...\n');

// Re-run key selfchecks
const selfchecks = [
  { name: 'env_completeness', script: 'infra/selfcheck/env_completeness.sh' },
  { name: 'ci_health', script: 'infra/selfcheck/ci_health.sh' },
];

for (const check of selfchecks) {
  if (existsSync(check.script)) {
    try {
      console.log(`  Running ${check.name}...`);
      execSync(`bash ${check.script}`, { stdio: 'pipe' });
      validationResults.regressionChecks[check.name] = 'pass';
      console.log(`    ✅ Passed`);
    } catch (e) {
      validationResults.regressionChecks[check.name] = 'fail';
      console.log(`    ❌ Failed`);
    }
  }
}

// Check issue status
for (const issue of issueRegister.issues) {
  if (issue.status === 'resolved') {
    validationResults.resolvedIssues.push(issue.id);
  } else {
    validationResults.remainingIssues.push({
      id: issue.id,
      title: issue.title,
      severity: issue.severity,
    });
  }
}

// Generate validation report
const report = `# Validation & Regression Report

**Generated**: ${validationResults.timestamp}

## Summary

### Resolution Status
- **Resolved Issues**: ${validationResults.resolvedIssues.length}
- **Remaining Issues**: ${validationResults.remainingIssues.length}

### Regression Checks
${Object.entries(validationResults.regressionChecks).map(([name, status]) => 
  `- **${name}**: ${status === 'pass' ? '✅ Pass' : '❌ Fail'}`
).join('\n')}

## Resolved Issues

${validationResults.resolvedIssues.length > 0 
  ? validationResults.resolvedIssues.map(id => `- ${id}`).join('\n')
  : '- None yet'
}

## Remaining Issues

${validationResults.remainingIssues.length > 0
  ? validationResults.remainingIssues.map(issue => 
      `### ${issue.id}: ${issue.title}\n- **Severity**: ${issue.severity}\n`
    ).join('\n')
  : '- All issues resolved! 🎉'
}

## Before/After Comparison

### Before Remediation
- Total Issues: ${issueRegister.totalIssues}
- Critical: ${issueRegister.bySeverity.critical}
- Major: ${issueRegister.bySeverity.major}
- Minor: ${issueRegister.bySeverity.minor}

### After Remediation
- Resolved: ${validationResults.resolvedIssues.length}
- Remaining: ${validationResults.remainingIssues.length}

## Next Steps

${validationResults.remainingIssues.length > 0
  ? `1. Review remaining ${validationResults.remainingIssues.length} issues
2. Apply fixes using generated scripts
3. Create PRs for each fix
4. Re-run validation after merge`
  : '✅ All issues resolved! No further action needed.'
}

---

*Generated by Validation & Regression Guard*
`;

writeFileSync(
  join(AUDIT_DIR, 'VALIDATION_REPORT.md'),
  report
);

writeFileSync(
  join(AUDIT_DIR, 'VALIDATION_REPORT.json'),
  JSON.stringify(validationResults, null, 2)
);

console.log(`\n✅ Validation complete!`);
console.log(`   - Resolved: ${validationResults.resolvedIssues.length}`);
console.log(`   - Remaining: ${validationResults.remainingIssues.length}`);
console.log(`\n📄 Report: ${join(AUDIT_DIR, 'VALIDATION_REPORT.md')}`);