#!/usr/bin/env tsx
/**
 * System Doctor
 * 
 * Self-healing system: generates delta migration, applies it, verifies DB.
 * If failure detected, opens a backlog ticket.
 * 
 * Usage:
 *   tsx scripts/agents/system_doctor.ts
 * 
 * Environment:
 *   SUPABASE_DB_URL (required) - PostgreSQL connection string
 */

import { execSync } from 'child_process';
import { logger } from '../lib/logger';
import { writeFileSync } from 'fs';
import { join } from 'path';

async function systemDoctor() {
  logger.info('🔍 System Doctor: Starting health check...');

  try {
    // Step 1: Generate delta migration
    logger.info('Step 1: Generating delta migration...');
    try {
      execSync('tsx scripts/agents/generate_delta_migration.ts', {
        stdio: 'inherit',
        env: process.env,
      });
      logger.info('✅ Delta migration generated');
    } catch (error) {
      logger.error('❌ Failed to generate delta migration:', error);
      throw error;
    }

    // Step 2: Apply migration (try Supabase CLI first, fallback to psql)
    logger.info('Step 2: Applying migration...');
    try {
      // Try Supabase CLI
      try {
        execSync('supabase db push --db-url "$SUPABASE_DB_URL" --include-all', {
          stdio: 'inherit',
          env: process.env,
          shell: true,
        });
        logger.info('✅ Migration applied via Supabase CLI');
      } catch (cliError) {
        logger.warn('⚠️  Supabase CLI failed, trying psql fallback...');
        // Fallback to psql
        const migrations = execSync('ls -1 supabase/migrations/*.sql | sort', {
          encoding: 'utf-8',
        })
          .trim()
          .split('\n');

        for (const migration of migrations) {
          execSync(`psql "$SUPABASE_DB_URL" -v ON_ERROR_STOP=1 -f "${migration}"`, {
            stdio: 'inherit',
            env: process.env,
            shell: true,
          });
        }
        logger.info('✅ Migration applied via psql');
      }
    } catch (error) {
      logger.error('❌ Failed to apply migration:', error);
      throw error;
    }

    // Step 3: Verify database
    logger.info('Step 3: Verifying database...');
    try {
      execSync('tsx scripts/agents/verify_db.ts', {
        stdio: 'inherit',
        env: process.env,
      });
      logger.info('✅ Database verification passed');
    } catch (error) {
      logger.error('❌ Database verification failed:', error);
      throw error;
    }

    logger.info('✅ System Doctor: All checks passed');
  } catch (error) {
    // Failure detected: create backlog ticket
    logger.error('❌ System Doctor: Failure detected. Creating ticket...');

    const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, -5);
    const ticketPath = join(
      process.cwd(),
      'backlog',
      `READY_system_fix_${timestamp}.md`
    );

    const ticket = `# READY: System Fix - ${timestamp}

**Type:** System Fix  
**Priority:** HIGH  
**Owner:** Engineering Lead  
**KPI:** System health checks pass  
**30-Day Signal:** System Doctor runs successfully, no failures detected

---

## Problem

System Doctor detected a failure during health check:
- Error: ${(error as Error).message}
- Timestamp: ${new Date().toISOString()}

---

## Solution

1. Review error message above
2. Check database connectivity
3. Verify migrations are applied
4. Run system doctor again after fixes

---

## Acceptance Criteria

- [ ] System Doctor runs successfully
- [ ] Database verification passes
- [ ] All migrations applied
- [ ] No errors detected

---

**Generated by:** System Doctor  
**Related:** \`/scripts/agents/system_doctor.ts\`
`;

    writeFileSync(ticketPath, ticket);
    logger.info(`✅ Ticket created: ${ticketPath}`);

    process.exit(1);
  }
}

systemDoctor().catch((error) => {
  logger.error('Fatal error:', error);
  process.exit(1);
});
